In [1]:
import pandas as pd
import plotly
import plotly.graph_objs as go
import plotly.offline as offline
from plotly.graph_objs import *
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot


init_notebook_mode(connected=True)

In [2]:
df = pd.read_csv('CASES-CURRENT.csv')

In [3]:
Cases = df[['id', 'date', 'province','age', 'travel_history', 'confirmed_presumptive']]
Cases.head()

,id,date,province,age,travel_history,confirmed_presumptive
0,1,1/25/2020,Ontario,50s,China,CONFIRMED
1,2,1/26/2020,Ontario,50s,China,CONFIRMED
2,3,1/28/2020,British Columbia,40s,China,CONFIRMED
3,4,1/31/2020,Ontario,20s,China,CONFIRMED
4,5,2/5/2020,British Columbia,50s,"None, but close contact with visitors from Hub...",CONFIRMED

In [4]:
province = pd.read_csv(r'C:\Users\msafari\Meysam Test Codes\COVID Map Projector\Data Files\Canada_Provinces.csv')
province.head()

                    province  Longitude    Latitude
0                    Alberta  53.933300 -116.576500
1           British Columbia  53.726669 -127.647621
2                   Manitoba  53.760860  -98.813873
3              New Brunswick  46.498390  -66.159668
4  Newfoundland and Labrador  53.135509  -57.660435

In [5]:
Cases = pd.merge(Cases, province, left_on='province', right_on='province')
Cases.head()

,id,date,province,age,travel_history,confirmed_presumptive,Longitude,Latitude
0,1,1/25/2020,Ontario,50s,China,CONFIRMED,51.2538,-85.3232
1,2,1/26/2020,Ontario,50s,China,CONFIRMED,51.2538,-85.3232
2,4,1/31/2020,Ontario,20s,China,CONFIRMED,51.2538,-85.3232
3,10,2/23/2020,Ontario,Adult (not further specified),"China, arrived two days prior on 21/02/20",CONFIRMED,51.2538,-85.3232
4,12,2/26/2020,Ontario,60s,Iran,CONFIRMED,51.2538,-85.3232

In [6]:
DailyCases = Cases.groupby(['date','province', 'Latitude', 'Longitude'])['date'].agg('count').to_frame('DailyCases').reset_index()
DailyCases.head()

        date          province    Latitude  Longitude  DailyCases
0  1/25/2020           Ontario  -85.323200  51.253800           1
1  1/26/2020           Ontario  -85.323200  51.253800           1
2  1/28/2020  British Columbia -127.647621  53.726669           1
3  1/31/2020           Ontario  -85.323200  51.253800           1
4  2/14/2020  British Columbia -127.647621  53.726669           1

In [7]:
scl = [[0.0, '#ffffff'],[0.2, '#ff9999'],[0.4, '#ff4d4d'], 
       [0.6, '#ff1a1a'],[0.8, '#cc0000'],[1.0, '#4d0000']] # reds

In [ ]:
data = [ dict(
            type='choropleth', # type of map-plot
            colorscale = scl,
            autocolorscale = False,
            locations = DailyCases['province'], # the column with the province/state
            z = DailyCases['DailyCases'].astype(float), # the variable I want to color-code
            locationmode = 'USA-states',
            text = df_sected_crime['text'], # hover text
            marker = dict(     # for the lines separating states
                        line = dict (
                                  color = 'rgb(255,255,255)', 
                                  width = 2) ),               
            colorbar = dict(
                        title = "Murder rate per 100,000 people")
            ) 
       ]